name: jekawin_mobile_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  responsive_builder: ^0.4.1
  shared_preferences: ^2.0.1
  share_plus:
  google_fonts: ^2.1.0
  get_storage: ^2.0.3
  cached_network_image: ^3.2.0
  logger: ^1.1.0
  oktoast: ^3.1.5
  gap: ^2.0.0
  flutter_svg: ^1.0.3
  pinput: ^2.2.5
  dartz: ^0.10.1
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  mockito: ^5.1.0
  flutter_platform_widgets: ^1.20.0
  hive: null
  hive_flutter: null
  image_picker:
  equatable: ^2.0.3
  path_provider: ^2.0.9
  custom_check_box: ^0.0.4
  bot_toast: ^4.0.1
  font_awesome_flutter: ^10.1.0
  flutter_switch: ^0.3.2
  webview_flutter: ^3.0.4
  modal_bottom_sheet:
  aws_s3_plugin_flutter: ^0.0.5

  #fire_base
#  cloud_firestore: ^3.4.4
#  firebase_core: ^1.20.1
#  firebase_messaging: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  hive_generator: null
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/jpgs/
    - dotenv
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700